[package]
authors = ["Zeke Sonxx <zeke@zekesonxx.com>"]
build = "build.rs"
name = "smaz-rs"
publish = false
version = "0.1.0"

[build-dependencies]
gcc = "0.3"

[dependencies]
lazy_static = "0.2.2"
libc = "0.2.20"
rand = "0.3.15"

[profile]

[profile.bench]
debug = true
